-- Trigger
CREATE OR REPLACE TRIGGER DISPLAY_SALARY_CHANGES
   BEFORE DELETE OR INSERT OR UPDATE ON DEMOTABLE
   FOR EACH ROW
   WHEN (NEW.DEMO_ID > 0)
DECLARE
   SAL_DIFF NUMBER;
BEGIN
   SAL_DIFF := :NEW.SALARY - :OLD.SALARY;
   DBMS_OUTPUT.PUT_LINE('Old salary: ' || :OLD.SALARY);
   DBMS_OUTPUT.PUT_LINE('New salary: ' || :NEW.SALARY);
   DBMS_OUTPUT.PUT_LINE('Salary difference: ' || SAL_DIFF);
END;
